### PR TITLE
202106 sync upstream

### PR DESCRIPTION
**Pull request by YuriiHordynskyi**
**- Why I did it**
To keep IMT 202106 branch in sync with the upstream 202106.
**- How I did it**
Backmerged the upstream 202106.
**- How to verify it**
Build the Barefoot and Broadcom targets.
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

```
yuriih@IMT-UA-MONSTER-Server:~/sonic-buildimage$ make all
. . .
SONiC Build System

Build Configuration
"CONFIGURED_PLATFORM"             : "broadcom"
"CONFIGURED_ARCH"                 : "amd64"
"SONIC_CONFIG_PRINT_DEPENDENCIES" : ""
"SONIC_BUILD_JOBS"                : "1"
"SONIC_CONFIG_MAKE_JOBS"          : "8"
"SONIC_USE_DOCKER_BUILDKIT"       : ""
"USERNAME"                        : "admin"
"PASSWORD"                        : "YourPaSsWoRd"
"ENABLE_DHCP_GRAPH_SERVICE"       : ""
"SHUTDOWN_BGP_ON_START"           : ""
"ENABLE_PFCWD_ON_START"           : ""
"SONIC_BUFFER_MODEL"              : ""
"INSTALL_DEBUG_TOOLS"             : ""
"ROUTING_STACK"                   : "frr"
"FRR_USER_UID"                    : "300"
"FRR_USER_GID"                    : "300"
"ENABLE_SYNCD_RPC"                : ""
"ENABLE_ORGANIZATION_EXTENSIONS"  : "y"
"HTTP_PROXY"                      : ""
"HTTPS_PROXY"                     : ""
"NO_PROXY"                        : ""
"ENABLE_ZTP"                      : ""
"SONIC_DEBUGGING_ON"              : ""
"SONIC_PROFILING_ON"              : ""
"KERNEL_PROCURE_METHOD"           : "build"
"BUILD_TIMESTAMP"                 : "20221111.162058"
"BUILD_LOG_TIMESTAMP"             : "none"
"SONIC_IMAGE_VERSION"             : "202106-sync-upstream.0-dirty-20221111.162058"
"BLDENV"                          : "buster"
"VS_PREPARE_MEM"                  : "yes"
"INCLUDE_MGMT_FRAMEWORK"          : "y"
"INCLUDE_ICCPD"                   : "n"
"INCLUDE_SYSTEM_TELEMETRY"        : "n"
"ENABLE_HOST_SERVICE_ON_START"    : "n"
"INCLUDE_RESTAPI"                 : "n"
"INCLUDE_SFLOW"                   : "y"
"INCLUDE_NAT"                     : "y"
"INCLUDE_DHCP_RELAY"              : "y"
"INCLUDE_KUBERNETES"              : "n"
"INCLUDE_MACSEC"                  : "y"
"TELEMETRY_WRITABLE"              : ""
"PDDF_SUPPORT"                    : "y"
"MULTIARCH_QEMU_ENVIRON"          : "n"
"SONIC_VERSION_CONTROL_COMPONENTS": "none"
"DEFAULT_CONTAINER_REGISTRY"      : ""
"SONIC_DPKG_CACHE_METHOD"         : "none"

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
make[1]: Leaving directory '/users/yuriih/sonic-buildimage'
yuriih@IMT-UA-MONSTER-Server:~/sonic-buildimage$ 

yuriih@IMT-UA-MONSTER-Server:~/sonic-buildimage$ ls -lah target/
total 6.7G
drwxrwxr-x  8 yuriih yuriih 4.0K Nov 11 17:02 .
drwxrwxr-x 20 yuriih yuriih 4.0K Nov 11 17:02 ..
drwxrwxrwx  2 yuriih yuriih 4.0K Nov 11 10:01 cache
drwxr-xr-x  5 yuriih yuriih 4.0K Nov 11 12:59 debs
-rw-r--r--  1 yuriih yuriih  87M Nov 11 14:06 docker-base-buster.gz
-rw-r--r--  1 yuriih yuriih   40 Nov 11 14:06 docker-base-buster.gz-load.log
-rw-r--r--  1 yuriih yuriih  57K Nov 11 14:05 docker-base-buster.gz.log
-rw-r--r--  1 yuriih yuriih 177M Nov 11 14:09 docker-config-engine-buster.gz
-rw-r--r--  1 yuriih yuriih   49 Nov 11 14:09 docker-config-engine-buster.gz-load.log
-rw-r--r--  1 yuriih yuriih  43K Nov 11 14:09 docker-config-engine-buster.gz.log
-rw-r--r--  1 yuriih yuriih 177M Nov 11 14:19 docker-database.gz
-rw-r--r--  1 yuriih yuriih 9.4K Nov 11 14:18 docker-database.gz.log
-rw-r--r--  1 yuriih yuriih 180M Nov 11 15:17 docker-dhcp-relay.gz
-rw-r--r--  1 yuriih yuriih  54K Nov 11 15:16 docker-dhcp-relay.gz.log
-rw-r--r--  1 yuriih yuriih 187M Nov 11 14:12 docker-fpm-frr.gz
-rw-r--r--  1 yuriih yuriih  28K Nov 11 14:12 docker-fpm-frr.gz.log
-rw-r--r--  1 yuriih yuriih 192M Nov 11 14:28 docker-lldp.gz
-rw-r--r--  1 yuriih yuriih  21K Nov 11 14:28 docker-lldp.gz.log
-rw-r--r--  1 yuriih yuriih 182M Nov 11 14:25 docker-macsec.gz
-rw-r--r--  1 yuriih yuriih  14K Nov 11 14:25 docker-macsec.gz.log
-rw-r--r--  1 yuriih yuriih 182M Nov 11 14:15 docker-nat.gz
-rw-r--r--  1 yuriih yuriih  19K Nov 11 14:15 docker-nat.gz.log
-rw-r--r--  1 yuriih yuriih 188M Nov 11 14:23 docker-orchagent.gz
-rw-r--r--  1 yuriih yuriih  38K Nov 11 14:22 docker-orchagent.gz.log
-rw-r--r--  1 yuriih yuriih 236M Nov 11 14:41 docker-platform-monitor.gz
-rw-r--r--  1 yuriih yuriih  88K Nov 11 14:41 docker-platform-monitor.gz.log
-rw-r--r--  1 yuriih yuriih 177M Nov 11 14:17 docker-router-advertiser.gz
-rw-r--r--  1 yuriih yuriih 7.2K Nov 11 14:16 docker-router-advertiser.gz.log
-rw-r--r--  1 yuriih yuriih 181M Nov 11 14:52 docker-sflow.gz
-rw-r--r--  1 yuriih yuriih  14K Nov 11 14:52 docker-sflow.gz.log
-rw-r--r--  1 yuriih yuriih 190M Nov 11 14:58 docker-snmp.gz
-rw-r--r--  1 yuriih yuriih  41K Nov 11 14:57 docker-snmp.gz.log
-rw-r--r--  1 yuriih yuriih 226M Nov 11 14:47 docker-sonic-mgmt-framework.gz
-rw-r--r--  1 yuriih yuriih  34K Nov 11 14:47 docker-sonic-mgmt-framework.gz.log
-rw-r--r--  1 yuriih yuriih 251M Nov 11 15:10 docker-syncd-brcm-dnx.gz
-rw-r--r--  1 yuriih yuriih  31K Nov 11 15:09 docker-syncd-brcm-dnx.gz.log
-rw-r--r--  1 yuriih yuriih 241M Nov 11 15:06 docker-syncd-brcm.gz
-rw-r--r--  1 yuriih yuriih  31K Nov 11 15:05 docker-syncd-brcm.gz.log
-rw-r--r--  1 yuriih yuriih 181M Nov 11 14:49 docker-teamd.gz
-rw-r--r--  1 yuriih yuriih  12K Nov 11 14:49 docker-teamd.gz.log
drwxr-xr-x  5 yuriih yuriih 4.0K Nov 11 10:01 files
drwxr-xr-x  2 yuriih yuriih 4.0K Nov 11 10:01 python-debs
drwxr-xr-x  2 yuriih yuriih  12K Nov 11 15:17 python-wheels
-rw-r--r--  1 yuriih yuriih 885M Nov 11 17:02 sonic-aboot-broadcom-dnx.swi
-rwxr-xr-x  1 yuriih yuriih 876M Nov 11 16:43 sonic-aboot-broadcom.swi
-rw-r--r--  1 yuriih yuriih 993K Nov 11 17:02 sonic-aboot-broadcom.swi.log
-rwxr-xr-x  1 yuriih yuriih 897M Nov 11 15:39 sonic-broadcom.bin
-rw-r--r--  1 yuriih yuriih 1.3M Nov 11 16:02 sonic-broadcom.bin.log
-rw-r--r--  1 yuriih yuriih 906M Nov 11 16:02 sonic-broadcom-dnx.bin
drwxrwxr-x  7 yuriih yuriih 4.0K Nov 11 17:01 versions

Success: Support tarball created: /tmp/onie-support-im_n29xx_t40n.tar.bz2
Installing for i386-pc platform.
Installation finished. No error reported.
Switch CPU vendor is: GenuineIntel
Switch CPU cstates are: disabled
Installed SONiC base image SONiC-OS successfully
ONIE:/ # 
. . .
Debian GNU/Linux 10 sonic ttyS0

sonic login: admin
Password: 
Linux sonic 4.19.0-12-2-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
You are on
  ____   ___  _   _ _  ____
 / ___| / _ \| \ | (_)/ ___|
 \___ \| | | |  \| | | |
  ___) | |_| | |\  | | |___
 |____/ \___/|_| \_|_|\____|

-- Software for Open Networking in the Cloud --

Unauthorized access and/or use are prohibited.
All access and/or use are subject to monitoring.

Help:    https://sonic-net.github.io/SONiC/

admin@sonic:~$ 
```

### CODE REVIEW

**Comment by YuriiHordynskyi** [comment]
@vitalivanov I suggest creating smth like the "202106-stable" branch based on the [InterfaceMasters:202106](https://github.com/InterfaceMasters/sonic-buildimage/tree/202106) for backup. On Monday, Nov 14 I am going to deploy the SONiC on one of our devices and if all is good will move the PR to the ready for review stage.

**Comment by vitalivanov** [comment]
i'm fine to create stable branch.
but one question - if we update only one repo to have more latest commits - wouldwe have issues as we do not update all the other repos? can be potentially problematic

let's see other guys feedback - @AndriiKit @oleksandrn-imt

**Comment by AndriiKit** [comment]
@vitalivanov @YuriiHordynskyi 
Speaking of InterfaceMasters SONiC top-level repo and it's submodules, we should be fine if succeeded to do next steps:
1. Update branch to the latest changes from upstream
2. Run git submodule update --init --recursive
3. Build SONiC
4. Install on BFN device and check if SDE started.

**Comment by vitalivanov** [comment]
so, we are pushing this after i create a branch from InterfaceMasters:202106->InterfaceMasters:202106-stable?

**Review by vitalivanov — APPROVED** [review]

**Review by AndriiKit — APPROVED** [review]

**Pull request merged**
